/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainRouteImport } from './routes/train'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DietRouteImport } from './routes/diet'
import { Route as IndexRouteImport } from './routes/index'

const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diet': typeof DietRoute
  '/history': typeof HistoryRoute
  '/targets': typeof TargetsRoute
  '/train': typeof TrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diet': typeof DietRoute
  '/history': typeof HistoryRoute
  '/targets': typeof TargetsRoute
  '/train': typeof TrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diet': typeof DietRoute
  '/history': typeof HistoryRoute
  '/targets': typeof TargetsRoute
  '/train': typeof TrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diet' | '/history' | '/targets' | '/train'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diet' | '/history' | '/targets' | '/train'
  id: '__root__' | '/' | '/diet' | '/history' | '/targets' | '/train'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DietRoute: typeof DietRoute
  HistoryRoute: typeof HistoryRoute
  TargetsRoute: typeof TargetsRoute
  TrainRoute: typeof TrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DietRoute: DietRoute,
  HistoryRoute: HistoryRoute,
  TargetsRoute: TargetsRoute,
  TrainRoute: TrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
